Adding a verbose query parameter to show more or less details in error msg
osu-mist/onbase-docs-api pull request #103
Opened 2023-04-07 19:03 UTC by fernamig

…r message.

2023-04-07 20:38 UTC, tsoliangwu0130 requested changes
Why would we want this to become a query parameter? This parameter is only for troubleshooting purposes and It's definitely not a feature this API really needs. An API should not behave differently based on applications/integration jobs. We should instead return an error object with only necessary information on its body (e.g. TrustFailure error). All other stack trace messages should be printed out at the API log level and can only be viewed by the API admins.

2023-04-10 22:53 UTC, tsoliangwu0130 reviewed
Changes look good for reverting back, but don't we want to expand errors anymore? I know expanding the entire error stack trace wasn't a good idea and it broke AWA jobs, but can't we just fetch the necessary info from the error stack trace? e.g. Just return TrustFailure error or Timeout error etc.

2023-04-10 23:06 UTC, fernamig commented
The useful errors is in the stack trace. Since AWA is not able to handle that we'll just revert to small message and add details in logging.

2023-04-10 23:08 UTC, tsoliangwu0130 approved these changes

2023-04-11 00:53 UTC, merged