Feature/CO-2036 unit tests
osu-mist/onbase-docs-api pull request #108
Opened 2023-05-08 20:54 UTC by fernamig

2023-05-08 21:08 UTC, tsoliangwu0130 commented
What's the issue? I ran `npm test` but didn't see any error.

2023-05-18 21:23 UTC, fernamig commented
This PR is ready to be reviewed. I resolved the issue that I mentioned in teams.

2023-05-18 21:52 UTC, tsoliangwu0130 requested changes

2023-05-18 21:52 UTC, tsoliangwu0130 commented on src/tests/unit/onbase-dao.test.js
> +import { createConfigStub } from './test-helpers';
Please adjust your import order to adhere to our JS coding style guide.

2023-05-18 21:52 UTC, tsoliangwu0130 commented on src/tests/unit/onbase-dao.test.js
> +describe('Test emails-dao', () => {
What is email-dao?

2023-05-18 21:52 UTC, tsoliangwu0130 commented on src/tests/unit/onbase-dao.test.js
> +  let onbaseDao2;
Please rename your variables and make them more descriptive.

2023-05-18 21:52 UTC, tsoliangwu0130 commented on src/tests/unit/onbase-dao.test.js
> +    );
What's the purpose of breaking lines here? Again, please ensure all of your code follows our coding conversion and follows the style guide. There are lots of styling issues among your codes; I'm not going to reply to them all individually.

2023-05-18 21:52 UTC, tsoliangwu0130 commented on src/tests/unit/onbase-dao.test.js
> +    });
Do you need all `onbaseDao`/`onbaseDao2` and `stubAxios`/`stubAxios2` for each test class? If not, why do you need to create all of them `beforeEach` and restore all of them at `afterEach`?

2023-05-18 21:52 UTC, tsoliangwu0130 commented on src/tests/unit/onbase-dao.test.js
> +  it('getAccessToken for valid profile should return a valid token',
What if `getAccessToken` got an invalid profile? and how about if the response is not 200?

Same comments with all of your other test cases. Besides successful/fulfilled cases, please also ensure they can catch the error as well.

2023-05-18 21:52 UTC, tsoliangwu0130 commented on src/tests/unit/onbase-dao.test.js
> +});
Besides DAO tests, you also need to test the serializers. Also, I updated `getAccessToken` function already to address users who might use the wrong stored cached credential, please make sure your code tested that part and reflect the change.

2023-06-16 00:54 UTC, tsoliangwu0130 requested changes
Much better. I left a few comments but all are very minor and are styling related.

2023-06-16 00:54 UTC, tsoliangwu0130 commented on src/tests/unit/documents-serializer.test.js
> +import { testMultipleResources, testSingleResource, createConfigStub } from './test-helpers';
A blank line is needed here for separating import groups.

2023-06-16 00:54 UTC, tsoliangwu0130 commented on src/tests/unit/test-helpers.js
> + * @returns {object} an error resonse object
typo: response.

2023-06-16 00:54 UTC, tsoliangwu0130 commented on src/tests/unit/documents-serializer.test.js
> +    };
Minor stuff, this fake document has been used multiple times, so it's better to store it in mock-data.js and reuse it.

2023-06-16 00:54 UTC, tsoliangwu0130 commented on src/tests/unit/documents-serializer.test.js
> +    const result = serializeDocuments([doc, doc], '');
Also a minor stuff, since all the other fake stuff you named "fake something", should this be named in the same way?

2023-06-16 00:54 UTC, tsoliangwu0130 commented on src/tests/unit/keywords-serializer.test.js
> +import proxyquire from 'proxyquire';
A blank line is also needed here.

2023-06-16 00:54 UTC, tsoliangwu0130 commented on src/tests/unit/keywords-serializer.test.js
> +    };
Same thing, I think this can be reused and stored in mock-data.js.

2023-06-16 00:54 UTC, tsoliangwu0130 commented on src/tests/unit/onbase-dao.test.js
> +import {
A blank line is needed here.

2023-06-16 00:54 UTC, tsoliangwu0130 commented on src/tests/unit/onbase-dao.test.js
> +};
Since you have mock-data.js, let's move all these fake data to there.

2023-06-16 00:54 UTC, tsoliangwu0130 commented on src/tests/unit/onbase-dao.test.js
> +const runErrorSuite = (testLabel, getter, errReturn, errThrowObj, errThrowMsg) => {
Can you also add document strings for this function as well?

2023-06-16 00:54 UTC, tsoliangwu0130 commented on src/tests/unit/keywords-serializer.test.js
> +  it('serializeKeywords should properly serialize keywords collection (GET) in JSON API format', () => {
In "Test keywords-serializer" and "Test documents-serializer", GET and POST tests are actually exactly the same besides the input method. You should be able to combine them with different var and use template strings to format the testing titles as you did in https://github.com/osu-mist/onbase-docs-api/pull/108/files#diff-c1a7ac1090dae64f3f41dfa948d89eae526e17bdc44df6ae83f4e0e21b471b3cR66

2023-06-30 23:54 UTC, tsoliangwu0130 approved these changes

2023-07-03 15:09 UTC, merged